BASE_URL_PATH: "api"
PORT: 8080
RPC_PORT: 9090

DB_HOST: localhost
DB_PORT: 5432
DB_USERNAME: postgres
DB_PASSWORD: postgres
DB_NAME: user_db
DB_MAX_OPEN_CONN: 20
DB_MAX_IDLE_CONN: 10
DB_MAX_LIFE_TIME: 30

REDIS_ADDRESS: "localhost:6739"
REDIS_PASSWORD: 
REDIS_DB: 0